
aws:
  s3:
    bucketName: ${BUCKET_NAME}
    accessKey: ${ACCESS_KEY}
    secretKey: ${SECRET_KEY}
    region: ${REGION}
    endpoint: ${ENDPOINT}

jwt:
  expirationTime: ${JWT_EXPIRATION_TIME}
  secret: ${JWT_SECRET}

spring:
  config:
    import: optional:secrets.yml

  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password: ''
  jpa:
    defer-datasource-initialization: true
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop


  h2:
    console:
      enabled: true
  sql:
    init:
      data-locations: "classpath*:db/data.sql"

logging:
  level:
    org.hibernate.SQL: TRACE
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE



