aws:
  s3:
    bucketName: ${BUCKET_NAME}
    accessKey: ${ACCESS_KEY}
    secretKey: ${SECRET_KEY}
    region: ${REGION}
    endpoint: ${ENDPOINT}

jwt:
  expirationTime: ${JWT_EXPIRATION_TIME}
  secret: ${JWT_SECRET}


app:
  baseUrl: ${BASE_URL}

spring:
  mail:
    host: ${MAIL_HOST}
    port: ${MAIL_PORT}
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  profiles:
    active: ${ACTIVE_PROFILE}

  config:
    import: optional:secrets.yml

  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: update

#  sql:
#    init:
#      data-locations: "classpath*:db/data.sql"
#      mode: always
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

logging:
  level:
    org.hibernate.SQL: TRACE
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE




