jwt:
  secret: "404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970"
  expirationTime: 86400000000000000

aws:
  s3:
    bucketName: "my-bucket-1"
    accessKey: "test"
    secretKey: "test"
    region: "us-east-1"
    endpoint: "http://localhost:4566/"

app:
  baseUrl: "localhost:8080"

spring:
  profiles:
    active: "dev"
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    url: "jdbc:postgresql://localhost:5432/mydb"
    username: "myuser"
    password: "mypassword"

  sql:
    init:
      platform: "postgres"
#  datasource:
#    url: jdbc:h2:mem:testdb
#    driverClassName: org.h2.Driver
#    username: sa
#    password: ''
#  jpa:
#    database-platform: org.hibernate.dialect.H2Dialect
#
#  h2:
#    console:
#      enabled: true
#      settings:
#        web-allow-others: true